
services:

  db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: app_dbi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1356
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./app_dbi.dump:/docker-entrypoint-initdb.d/app_dbi.dump
      - ./restore_db.sh:/docker-entrypoint-initdb.d/restore_db.sh
    networks:
      - app_dbi

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      - "5672:5672"
    networks:
      - app_dbi

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=root
      - ES_JAVA_OPTS=-Xms512m -Xmx1024m
    ports:
      - "9200:9200"
    networks:
      - app_dbi
    volumes:
      - ./es_data:/usr/share/elasticsearch/data

  app_dbi_core:
    build:
      context: app_dbi_core
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/app_dbi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1356
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: root
      SPRING_RABBITMQ_PASSWORD: root
      TRANSACTIONS_SERVICE_API_URL: app_dbi_transactions
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - app_dbi

  app_dbi_transactions:
    build:
      context: app_dbi_transactions
      dockerfile: Dockerfile
    environment:
      SPRING_ELASTICSEARCH_URI: elasticsearch
      SPRING_ELASTICSEARCH_USERNAME: elastic
      SPRING_ELASTICSEARCH_PASSWORD: root
    depends_on:
      - app_dbi_core
      - rabbitmq
      - elasticsearch
    ports:
      - "8081:8081"
    networks:
      - app_dbi

volumes:
  es_data:
    driver: local

networks:
  app_dbi:
    driver: bridge