FROM openjdk:23-jdk-slim AS build

WORKDIR /app

COPY gradle /app/gradle
COPY gradlew /app
COPY build.gradle /app
COPY settings.gradle /app
COPY src /app/src

RUN chmod +x gradlew

RUN ./gradlew build -x test --no-daemon

FROM openjdk:23-jdk-slim

WORKDIR /app

COPY --from=build /app/build/libs/*.jar /app/app.jar
COPY --from=build /app/src/main/webapp /app/src/main/webapp

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]