FROM openjdk:23-jdk-slim AS build

WORKDIR /app

COPY gradle /app/gradle
COPY gradlew /app
COPY build.gradle /app
COPY dbi_core/settings-docker.gradle /app
COPY dbi_core/build.gradle /app/dbi_core/
COPY dbi_core/src /app/dbi_core/src
COPY common/build.gradle /app/common/
COPY common/src /app/common/src

RUN chmod +x gradlew

RUN ./gradlew -settings-file settings-docker.gradle build -x test --no-daemon

FROM openjdk:23-jdk-slim

WORKDIR /app

COPY --from=build /app/dbi_core/build/libs/*.jar /app/app.jar
COPY --from=build /app/dbi_core/src/main/webapp /app/src/main/webapp

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]