FROM openjdk:23-jdk-slim AS build

WORKDIR /app

COPY gradle /app/gradle
COPY gradlew /app
COPY build.gradle /app
COPY settings.gradle /app
COPY src /app/src

RUN chmod +x gradlew

RUN ./gradlew build -x test --no-daemon

FROM openjdk:23-jdk-slim

RUN apt-get update && apt-get install -y curl && apt-get clean

COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

WORKDIR /app

COPY --from=build /app/build/libs/*.jar /app/app.jar

EXPOSE 8081

ENTRYPOINT ["wait-for-it.sh", "http://elasticsearch:9200", "-t", "30", "--", "java", "-jar", "/app/app.jar"]